SELECT REPLACE(PHONE_NUMBER, '515', '777') FROM hr.employees WHERE PHONE_NUMBER LIKE '515%';
UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';
SELECT * FROM hr.employees WHERE LENGTH(FIRST_NAME) > 8;
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;
