SELECT UCASE(FIRST_NAME) FROM hr.employees;
SELECT LAST_NAME, HIRE_DATE FROM hr.employees 
WHERE YEAR(HIRE_DATE) = 1987 AND MONTH(HIRE_DATE) = 7;
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM hr.employees;